version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend_cephalea
    volumes:
      - .:/app  
      - /app/node_modules  
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  
    command: ["npm", "run", "dev", "--", "--host"]
